import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { EdgeBlockedError } from '@chrischall/mcp-utils';
import { createTestHarness } from '@chrischall/mcp-utils/test';
import { ViboClient } from '../src/client.js';
import { registerProfileTools } from '../src/tools/profile.js';

// A CloudFront WAF refusal (the page Zola served on 2026-10-01). It answers
// 403, which this client read as "you don't have permission in this event —
// ask the host or DJ", and on a refresh it ended in "sign in again". Neither
// is true: the request never reached Vibo.
const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: abc123==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;

const blocked = () =>
  new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront' },
  });

const ENV_KEYS = ['VIBO_EMAIL', 'VIBO_PASSWORD', 'VIBO_ACCESS_TOKEN', 'VIBO_REFRESH_TOKEN', 'VIBO_API_URL', 'VIBO_SESSION_FILE'];
let sessionDir: string;
let realFetch: typeof fetch;
beforeEach(() => {
  for (const k of ENV_KEYS) delete process.env[k];
  sessionDir = mkdtempSync(join(tmpdir(), 'vibo-edge-'));
  process.env.VIBO_SESSION_FILE = join(sessionDir, 'session.json');
  realFetch = global.fetch;
});
afterEach(() => {
  global.fetch = realFetch;
  vi.restoreAllMocks();
  rmSync(sessionDir, { recursive: true, force: true });
  for (const k of ENV_KEYS) delete process.env[k];
});

describe('CDN/WAF edge blocks', () => {
  it('vibo_healthcheck names a CloudFront 403 block page instead of a permission denial', async () => {
    global.fetch = vi.fn(async () => blocked()) as unknown as typeof fetch;
    const client = new ViboClient({ accessToken: 'AT', refreshToken: 'RT' });
    const h = await createTestHarness((s) => registerProfileTools(s, client));
    const res = await h.callTool('vibo_healthcheck');
    expect(res.isError).toBe(true);
    const text = JSON.stringify(res.content);
    expect(text).toMatch(/CDN\/WAF \(CloudFront\)/);
    expect(text).not.toMatch(/permission/i);
    await h.close();
  });

  it('a blocked refresh surfaces the block and keeps the stored tokens', async () => {
    // The access token is rejected (401), and the refresh-token grant then meets the WAF.
    const fetchMock = vi.fn(async (_url: unknown, init: { body: string }) =>
      init.body.includes('mutation refreshToken')
        ? blocked()
        : new Response(JSON.stringify({ errors: [{ code: 'UNAUTHORIZED', message: 'Not authorized' }] }), { status: 401 }),
    );
    global.fetch = fetchMock as unknown as typeof fetch;
    const client = new ViboClient({ accessToken: 'AT', refreshToken: 'RT' });
    const err = await client.gql('query getMe { me { _id } }').catch((e) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect(err.status).toBe(403);
    // Nothing rotated or overwritten: the refresh token is still the one we had.
    expect(existsSync(process.env.VIBO_SESSION_FILE!)).toBe(false);
    const retry = fetchMock.mock.calls.length;
    await client.gql('query getMe { me { _id } }').catch(() => {});
    const refreshBodies = fetchMock.mock.calls.slice(retry).map((c) => (c[1] as { body: string }).body);
    expect(refreshBodies.some((b) => b.includes('"refreshToken":"RT"'))).toBe(true);
  });

  it('a plain HTTP 403 from the API is still a permission denial', async () => {
    global.fetch = vi.fn(async () => new Response('{}', { status: 403 })) as unknown as typeof fetch;
    const client = new ViboClient({ accessToken: 'AT' });
    await expect(client.gql('mutation updateSection { x }')).rejects.toThrow(/permission/i);
  });
});
